services:
    app:
        build:
            context: ./backend
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./backend:/var/www
        depends_on:
            - redis
            - bun
            - mysql
        networks:
            - laravel
        environment:
            XDEBUG_MODE: debug,develop
            XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003"
            APP_ENV: local
            APP_DEBUG: "true"
            APP_KEY: "base64:3H9y5VJ0hA1g2K8vLw4n1qS9mQe7XyZ0jVdF6oPlq9o="
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: laravel
            DB_USERNAME: laravel
            DB_PASSWORD: secret
            REDIS_HOST: redis
        extra_hosts:
            - "host.docker.internal:host-gateway"

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./docker/nginx/laravel.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel
        depends_on:
            - app
            - bun

    bun:
        image: oven/bun:latest
        restart: unless-stopped
        working_dir: /app
        build:
            context: ./frontend
        volumes:
            - ./frontend/:/app
        networks:
            - laravel
        entrypoint:
            - "bun"
            - "run"
            - "dev"

    redis:
        image: redis:latest
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: secret
            MYSQL_USER: laravel
        volumes:
            - mysql2:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
            interval: 5s
            timeout: 5s
            retries: 20

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root
        networks:
            - laravel
        depends_on:
            - mysql

networks:
    laravel:
        driver: bridge

volumes:
    mysql:
        driver: local
    mysql2:
        driver: local