services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        ports:
            - "80:80"
            - "5173:5173"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - node
        networks:
            - laravel
        environment:
            XDEBUG_MODE: debug,develop
            XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003"
        extra_hosts:
            - "host.docker.internal:host-gateway"

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    node:
        image: node:22
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravel

    redis:
        image: redis:latest
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: secret
            MYSQL_USER: laravel
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root
        networks:
            - laravel
        depends_on:
            - mysql

networks:
    laravel:
        driver: bridge

volumes:
    mysql:
        driver: local